version: '3'

services:

  app_fastapi:
    container_name: app_fastapi
    build: ./app
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
    depends_on: 
      - mongo_db
      - redis_db

  ui_vue:
    container_name: ui_vue
    build: ./ui/vue-app
    ports:
      - '5001:5001'
    restart: unless-stopped
    volumes:
      - ./ui/vue-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - npm_config_unsafe_perm=true

  redis_db:
    container_name: redis_db
    image: redis:6-buster
    restart: unless-stopped
    ports:
      - '6379:6379'
    
  mongo_db:
    container_name: mongo_db
    image: mongo:4.2-bionic
    restart: unless-stopped
    ports:
      - '27017:27017'
      
  mongo_express:
    container_name: mongo_express
    image: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on: 
      - mongo_db
