version: '3'

services:

  api:
    container_name: api
    build: ./app
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
    depends_on: 
      - mongo


  ui:
    container_name: ui
    build: ./ui/vue-app
    ports:
      - '5001:5001'
    restart: unless-stopped
    volumes:
      - ./ui/vue-app:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - npm_config_unsafe_perm=true

  mongo:
    container_name: mongo
    image: mongo:4.2-bionic
    restart: unless-stopped
    ports:
      - '27017:27017'
    
      
  mongo-express:
    container_name: mongo-dashboard
    image: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on: 
      - mongo

    
    

