version: '3'

services:

  api:
    build: ./app
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app

  ui:
    build: ./ui/vue-app
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - ./ui/vue-app:/usr/src/app
   
    
    

